import { Injectable } from '@angular/core';
import { of } from 'rxjs';

interface Record {
  name: string;
}

@Injectable({
  providedIn: 'root'
})
export class DataService {
  private data = [
    { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'John' },
      { name: 'Jane' },
      { name: 'Bob' },
      { name: 'Rekha' },
      { name: 'Rekha' },
      { name: 'Rekha' },
      { name: 'Rekha' },
      { name: 'Rekha' },
      { name: 'Rekha' },
      { name: 'Rekha' },
      { name: 'Rekha' },
      { name: 'Rekha' },
      { name: 'Ram' },
      { name: 'Ram' },
      { name: 'Ram' },
      { name: 'Ram' },
      { name: 'Ram' },
      { name: 'Ram' },
      { name: 'Ram' },
      { name: 'Ram' },
      { name: 'Ram' },
      { name: 'Ravi' },
      { name: 'Ram' },
      { name: 'Raj' },
      { name: 'Ravi' },
      { name: 'Rani' },
      { name: 'Raj' },
      { name: 'Ravi' }
  ];

  constructor() { }

  getData() {
    return of(this.data);
  }
}
